// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkYxb2uKtIv0L-qxNMheYMWLjvYmaLM0g',
    appId: '1:1024540995852:web:e8b61cea76b171e90d9929',
    messagingSenderId: '1024540995852',
    projectId: 'cricket-scoring-app-64036',
    authDomain: 'cricket-scoring-app-64036.firebaseapp.com',
    storageBucket: 'cricket-scoring-app-64036.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjYONkYGFVyPk8lG7nLfB0ZUt-pYZrI-Y',
    appId: '1:1024540995852:android:b4d4a22e69e331f20d9929',
    messagingSenderId: '1024540995852',
    projectId: 'cricket-scoring-app-64036',
    storageBucket: 'cricket-scoring-app-64036.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEZDXW9FWa6F8efcccjHqjsnKVRy4riW8',
    appId: '1:1024540995852:ios:a0564b83843a04030d9929',
    messagingSenderId: '1024540995852',
    projectId: 'cricket-scoring-app-64036',
    storageBucket: 'cricket-scoring-app-64036.firebasestorage.app',
    iosBundleId: 'com.example.cricketScoringApp',
  );
}
